---
- hosts: localhost
  tasks:
    - name: Remove AWS Step Functions state machine "{{ name }}"
      community.aws.aws_step_functions_state_machine:
        name: "{{ name }}"
        state: absent
    
    - name: "Remove EventBrdige ruel if scheduling expression was defined"
      community.aws.cloudwatchevent_rule:
        name: "{{ name }}-EventBridgeRule"
        state: absent
      when: (schedule_expression is defined) and (schedule_expression != "none")
