---
- name: Update AWS state machine with correct function ARN
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run update script
      command: /usr/bin/python3 arn-updater.py {{ state_machine }} {{ function_name }} {{ function_arn }}